image: amos6224/postgres9.2
script:
  - apt-get update
  - sleep 10
  - /etc/init.d/postgresql start
  - /etc/init.d/redis start
  - apt-get install -y git
  - apt-get install -y imagemagick libxslt1-dev libxml2-dev libpq-dev
  - cp config/database.drone.yml config/database.yml
  - cp .env.example .env
  - RAILS_ENV=test bundle exec rake db:test:load
  - RAILS_ENV=test bundle exec rspec spec

notify:
  email:
    recipients:
      - jeff@namely.com

  hipchat:
    room: CI
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true
