image: amos6224/namely.3
script:
  - apt-get update
  - sleep 10
  - /etc/init.d/postgresql start
  - /etc/init.d/redis_6379 start
  - apt-get install -y git
  - apt-get install -y screen
  - apt-get install -y htop
  - apt-get install -y imagemagick libxslt1-dev libxml2-dev libpq-dev sqlite3 libsqlite3-dev
  - gem install execjs
  - cd /tmp
  - rails new namely
  - cd namely
  - bundle install
  - expose 3000

notify:
  email:
    recipients:
      - jeff@namely.com

  hipchat:
    room: CI
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true
