image: amos6224/namely.3
service:
  - redis
  - postgres

script:
  - sleep 1
  - psql -c 'create database test' -U postgres -h 127.0.0.1
  - apt-get update
  - apt-get install -y git
  - apt-get install -y screen
  - apt-get install -y htop
  - apt-get install -y imagemagick libxslt1-dev libxml2-dev libpq-dev sqlite3 libsqlite3-dev
  - gem install execjs
  - cd /tmp
  - rails new namely
  - cd namely
  - bundle install


notify:
  email:
    recipients:
      - jeff@namely.com
      
    urls:
      - http://www.namely.com:3000

  hipchat:
    room: CI
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true
