image: amos6224/namely.3
script:
  - apt-get -y update
  - apt-get install -y nginx
  - apt-get install -y imagemagick libxslt1-dev libxml2-dev libpq-dev sqlite3 libsqlite3-dev

service:
  - redis
  - postgres

notify:
  email:
    recipients:
      - jeff@namely.com

 webhook:
    on_success: true
    on_failure: true
    urls:
      - http://www.namely.com:3000

  hipchat:
    room: CI
    token: {{hipchat_token}}
    on_started: true
    on_success: true
    on_failure: true
